### ISSUE TITLE
Logo design for locus

### ISSUE THREAD

**Issue by reallinfo** [g-andrade/locus#1]
Hello! I am a graphic designer. I contribute to open source software via logo design. If you want, i can design a logo for locus. Actually, I have a my logo idea.  If you have an idea, you can say it.

I will waiting feedback. Have a nice day!

**Comment by g-andrade** [comment]
Hi,

I'm thankful for the offer, but for now I'm not looking for a logo - I don't think locus is fancy or big enough to even deserve one :-) I believe it could give off the impression that it does more than it actually does.

A nice day to you too; and thanks again!
