### ISSUE TITLE
Provide REBAR2 config for locus

### ISSUE THREAD

**Issue by yhafri** [g-andrade/locus#13]
Hi @g-andrade 
Can you please provide a rebar.config we can use with REBAR2?
Thanks

**Comment by g-andrade** [comment]
I've restored it in [`1.10.2`](https://github.com/g-andrade/locus/commit/107bc16165b008f178500b8195b7c06b56698d06).

Bear in mind this could stop working at any moment in the near future - it's no longer practical to ensure compatibility with rebar 2.
I strongly suggest you move to `rebar3` if and when it's possible for you to do so.

Closing this; please reopen if you find any issues.

**Comment by g-andrade** [comment]
I've permanently dropped support in `1.15.0` due to the hack required no longer remaining feasible.
