### ISSUE TITLE
Broken code

### ISSUE THREAD

**Issue by manudatta** [g-andrade/locus#3]
Looks like the code is broken. I tried both the example and trying loading the local file.

1> URL = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz".
"https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
2> locus:start_loader(country, URL).
** exception exit: {noproc,
                       {gen_server,call,
                           [locus_sup,
                            {start_child,
                                {{http_loader,country},
                                 {locus_http_loader,start_link,
                                     [country,
                                      "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz",
                                      [{event_subscriber,locus_logger}]]},
                                 permanent,5000,worker,
                                 [locus_http_loader]}},
                            infinity]}}
     in function  gen_server:call/3 (gen_server.erl, line 214)
     in call from locus_sup:start_child/3 (/Users/manu/misc/ex/_build/default/lib/locus/src/locus_sup.erl, line 67)

**Comment by g-andrade** [comment]
Did you solve whatever was the problem? The log excerpt suggests the application wasn't started. If you launch the shell by running `make console` it should start it automatically for you. Otherwise, if you're importing the library as a dependency, including it in `app.src` should do it, too.

**Comment by manudatta** [comment]
Yes I did realise it is an app.
Thanks a lot for creating this wonderful library.
Regards
Manu
