### ISSUE TITLE
How to use the database provided by the OS?

### ISSUE THREAD

**Issue by leoliu** [g-andrade/locus#6]
My CentOS provides an update-to-date DB: `/usr/share/GeoIP/GeoLite2-City.mmdb`. But `locus` seems to want a tar ball instead. Is it possible to make it support system-provided DB which simplifies deployment a lot? Thanks.

**Comment by g-andrade** [comment]
I've got some unreleased changes under the `develop` branch that would make this reasonably easy to implement.

I'll leave this issue open as a reminder.

**Comment by g-andrade** [comment]
I've added experimental support for direct load of `.mmdb` files on 7477a1cd4dc (yet unreleased.)

Please try it and let me know whether that works for you.
```erlang
URL = "/usr/share/GeoIP/GeoLite2-City.mmdb",
ok = locus:start_loader(city, URL).
```

**Comment by leoliu** [comment]
I just tested it with the `develop` and it works like a charm. Thanks a lot for the quick fix.

**Comment by g-andrade** [comment]
A new version, `1.7.0`, has been released and it includes support for [multiple file formats](https://github.com/g-andrade/locus/tree/1.7.0#supported-file-formats), including unpacked `mmdb` files.

Closing this; please re-open (or open a new issue) if you find any problems.
