### ISSUE TITLE
Changes to GeoLite2 license and distribution require changes to this project

### ISSUE THREAD

**Issue by 2shortplanks** [g-andrade/locus#9]
The direct download mechanism that you are currently using will no longer function after December 30th 2019.

Due to upcoming data privacy regulations, MaxMind are making significant changes to how users access free MaxMind GeoLite2 databases starting December 30, 2019. The databases will continue to be available without charge and for redistribution. However, you will be required to create an account and use a license key to download the databases, and agree to a new EULA that addresses applicable data privacy regulations.

Learn more on the MaxMind blog: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/.

Mark Fowler
MaxMind

**Comment by g-andrade** [comment]
Mmmh.. well, it it what is is. It was a good run. I'll solve it when I get a chance, thanks for the notice!

**Comment by g-andrade** [comment]
I've created an account and got my hands on a license key. 

Now, maybe I'm just being dense, but the new authenticated links for [direct downloads](https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads) don't appear to be available yet; I'll try again in a near future in order to update documentation appropriately, using a realistic example.

**Comment by g-andrade** [comment]
> the new authenticated links for direct downloads don't appear to be available yet

![Screenshot at 2019-12-21 17-40-47](https://user-images.githubusercontent.com/7349502/71311686-21519b00-2419-11ea-8084-f91352f8073e.png)

-------------------------
`Show archived database files` leads me to another empty list. Do I need to perform a "purchase" of the free GeoLite2 databases in order for them to show up on the list?

**Comment by g-andrade** [comment]
I've re-read the [blog post](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/) and paid actual attention to the content this time; I'm guessing everything will be clearer by December 23rd.

**Comment by oschwald** [comment]
The blog post has been updated with the new license and sign-up details.

**Comment by g-andrade** [comment]
`locus 1.9.0-beta` has been released; it's license key -aware.

**Comment by g-andrade** [comment]
Closing this as the beta showed no problems whatsoever and `locus 1.9.0` has just been released.
